### ISSUE TITLE
loss is nan when using fp16 mixed precision

### ISSUE THREAD

**Issue by JaheimLee** [AtlasAnalyticsLab/AdaFisher#1]
Can we use adafisher with fp16?

**Comment by Damien3008** [comment]
Hello, during all the experiments AdaFisher was used with fp32 mixed precision as it is the default precision in PyTorch. Thank you for your question, we are going to investigate on this issue ASAP.

**Comment by Damien3008** [comment]
Hello, AdaFisher is now working with fp16 precision. I added in config files a new parameter "precision" where you can choose between fp16 and fp32. Please notice that AdaHessian, K-FAC, and Shampoo only work with fp32 precision. If you have any other problem don't hesitate to contact me, and thank you for your message.

**Comment by JaheimLee** [comment]
thanks
